# Server Configuration
server:
  port: ${GATEWAY_SERVER_PORT}

# API Configuration
app:
  api-prefix: /api/v1

# Application Name
spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: profile-service
          uri: http://localhost:9001
          predicates:
            - Path=${app.api-prefix}/profiles/**
          filters:
            - RewritePath=${app.api-prefix}/profiles/(?<segment>.*), /profile/$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.apigateway: DEBUG
