spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
