server:
  port: ${ORDER_SERVER_PORT:9002}
  servlet:
    context-path: /

spring:
  application:
    name: order-service
  cloud:
    compatibility-verifier:
      enabled: false

  # PostgreSQL Database
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${ORDER_DB_USERNAME:root}
    password: ${ORDER_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # OAuth2 Resource Server Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/pureevilstore/protocol/openid-connect/certs}

  # Kafka Cluster & Saga Listener
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

# Inter-service URLs for OpenFeign
app:
  services:
    product-service:
      url: http://localhost:9005
    payment-service:
      url: http://localhost:9003

# Config Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Config SpringDoc / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
