server:
  port: ${PRODUCT_SERVER_PORT:9005}
  servlet:
    context-path: /

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${PRODUCT_MONGODB_URI:mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER_HOST}/${MONGODB_DATABASE:product_db}?retryWrites=true&w=majority&appName=${MONGODB_APP_NAME:pure-evil-store}}
  # Cấu hình Kafka Consumer để lắng nghe event từ profile-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Cấu hình Brevo gửi Email (Lấy từ notification-service cũ của bạn)
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${BREVO_API_KEY}

# Config Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

# Config SpringDoc / Swagger UI cho Product Service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
