server:
  port: ${PROFILE_SERVER_PORT}
  servlet:
    context-path: /

spring:
  application:
    name: profile-service
  cloud:
    compatibility-verifier:
      enabled: false
  # PostgreSQL Database
  datasource:
    url: ${PROFILE_DB_URL}
    username: ${PROFILE_DB_USERNAME}
    password: ${PROFILE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

# Config Identity Service
identity-service:
  url: ${IDENTITY_SERVICE_URL}
  client-id: ${IDENTITY_CLIENT_ID}
  client-secret: ${IDENTITY_CLIENT_SECRET}
  realm-name: ${IDENTITY_REALM_NAME}

# Config AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

# Config Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# Config SpringDoc / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
